name: "Containers"
description: "Builds and optionally pushes container images"

inputs:
  container-registry-server:
    description: "Container registry server"
    default: "docker.io"
    required: false
  container-registry-username:
    description: "Container registry username"
    required: false
  container-registry-password:
    description: "Container registry password"
    required: false
  wemogy-packages-token:
    description: "The token to use to authenticate with the wemogy-packages service"
    required: true
  version:
    description: "The version of the container image"
    required: true
  push:
    description: "Whether to push the container image to the registry"
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Login to Azure Container Registry
      if: inputs.push == 'true'
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.container-registry-server }}
        username: ${{ inputs.container-registry-username }}
        password: ${{ inputs.container-registry-password }}

    - name: Build and push Container image
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        push: ${{ inputs.push }}
        tags: ${{ inputs.container-registry-server }}/subscriptions-main:${{ inputs.version }}

    # Add build steps for additional containers here...
